# Generated by Django 5.0.6 on 2024-05-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sliders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
