# Generated by Django 5.0.6 on 2024-05-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_about_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image2',
        ),
    ]
